### ISSUE TITLE
Please add Ionicons

### ISSUE THREAD

**Issue by BerkeAras** [Futureglobe/Simpico_IssueTracker#1]
Hello!

Could you please add Ionicons? That would be great!
Thanks!

**Comment by Futureglobe** [comment]
Hi Berke,

Thank you for the request.
We just added Ionicons as a resource to the app with the new update.

![ScreenshotSimpico](https://user-images.githubusercontent.com/27356972/55009674-41b40c80-4fe3-11e9-8739-30c6621d4295.PNG)

When you open up the app it should ask you to update.
