### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by victmo** [Futureglobe/Simpico_IssueTracker#3]
**Name:** Feature request
**About:** Suggest an idea for this project

---

**Is your feature request related to a problem?**
I was unable to download a Mac version of your app on your website. Are you planning on releasing one?

**Describe the solution you'd like**
Electron allows you to deploy to multiple operating systems.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Futureglobe** [comment]
Hello @victmo thanks for your feature request.
We are currently working on releasing a mac version of SimpIco.
Also, we are doing some major improvements so it might take a while.
We will let you know as soon as its ready.

Your Futureglobe Support Team

**Comment by victmo** [comment]
Thanks :)

**Comment by Futureglobe** [comment]
Hi @victmo, 

As promised we will inform you that we have now released a Simpico Mac version. This version is identical to the features of the Windows version. 
You can download the mac version on the official website : https://simpico.futureglobe.de/

Your Futureglobe Support Team
